/* Autogenerated with kurento-module-creator */

#include "MeetrixKurentoHelloWorldOpenCVImpl.hpp"
#include <KurentoException.hpp>

namespace kurento
{
namespace module
{
namespace meetrixkurentohelloworld
{

MeetrixKurentoHelloWorldOpenCVImpl::MeetrixKurentoHelloWorldOpenCVImpl ()
{
    textToPrint = "Hello From Meetrix";
    positionX = 100;
    positionY = 100;
}

/*
 * This function will be called with each new frame. mat variable
 * contains the current frame. You should insert your image processing code
 * here. Any changes in mat, will be sent through the Media Pipeline.
 */
void MeetrixKurentoHelloWorldOpenCVImpl::process (cv::Mat &mat)
{
    cv::Point textOrg(positionX, positionY);
    putText( mat, textToPrint, textOrg, 1, 2, cv::Scalar(0, 0, 0) );
}

void MeetrixKurentoHelloWorldOpenCVImpl::setText(const std::string &text, const int x, const int y)
{
    textToPrint= text;
    positionX= x;
    positionY= y;
}




} /* meetrixkurentohelloworld */
} /* module */
} /* kurento */
