/* Autogenerated with kurento-module-creator */

#ifndef __MEETRIX_KURENTO_HELLO_WORLD_IMPL_HPP__
#define __MEETRIX_KURENTO_HELLO_WORLD_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "MeetrixKurentoHelloWorld.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "MeetrixKurentoHelloWorldOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace meetrixkurentohelloworld
{
class MeetrixKurentoHelloWorldImpl;
} /* meetrixkurentohelloworld */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::meetrixkurentohelloworld::MeetrixKurentoHelloWorldImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace meetrixkurentohelloworld
{

class MeetrixKurentoHelloWorldImpl : public OpenCVFilterImpl, public virtual MeetrixKurentoHelloWorld, public virtual MeetrixKurentoHelloWorldOpenCVImpl
{

public:

  MeetrixKurentoHelloWorldImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~MeetrixKurentoHelloWorldImpl () {};

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);
  void setText(const std::string &text, const int x, const int y);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* meetrixkurentohelloworld */
} /* module */
} /* kurento */

#endif /*  __MEETRIX_KURENTO_HELLO_WORLD_IMPL_HPP__ */
